# Funding platforms for nowo-tech/php-quality-tools
# These are supported funding model platforms

github: [HecFranco]
# patreon: 
# open_collective: 
# ko_fi: 
# tidelift: 
# community_bridge: 
# issuehunt: 
# otechie: 
# lfx_crowdfunding: 
# custom: 

